POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "username": "moi123",
  "first_name": "Pekka23",
  "last_name": "Testaaja32",
  "password": "6456456"
}

###
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testaaja2",
  "password": "salainen"
}

###
GET http://localhost:8000/api/images/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY2OTYwLCJpYXQiOjE3MzkzNjUxNjAsImp0aSI6ImZiNjFhOWViNzY0NjRmMGY4NTU0MGM1MDM1Njg3MGJlIiwidXNlcl9pZCI6Mn0.b16QouwjeJLm8DIchsiJdTYMecyKZsqmhWuyFk_eJ-U
Content-Type: application/json

{
  "image_url": "https://www.paramountshop.com/cdn/shop/files/spongebob-squarepants-life-sized-cardboard-cutout-standee-725187.jpg?v=1718292084"
}

#user should not be able to delete other user
###
GET http://localhost:8000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY2OTYwLCJpYXQiOjE3MzkzNjUxNjAsImp0aSI6ImZiNjFhOWViNzY0NjRmMGY4NTU0MGM1MDM1Njg3MGJlIiwidXNlcl9pZCI6Mn0.b16QouwjeJLm8DIchsiJdTYMecyKZsqmhWuyFk_eJ-U