"""empty message

Revision ID: 9ec1aea65572
Revises: 29747da5a1ca
Create Date: 2025-07-28 15:55:15.624520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ec1aea65572"
down_revision: Union[str, None] = "29747da5a1ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("competition_entries_competition_id_fkey"),
        "competition_entries",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "competition_entries",
        "competitions",
        ["competition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("pairwise_votes_winner_entry_id_fkey"),
        "pairwise_votes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("pairwise_votes_loser_entry_id_fkey"), "pairwise_votes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("pairwise_votes_competition_id_fkey"), "pairwise_votes", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "pairwise_votes",
        "competitions",
        ["competition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "pairwise_votes",
        "competition_entries",
        ["winner_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "pairwise_votes",
        "competition_entries",
        ["loser_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.execute("ALTER TYPE competition_status ADD VALUE IF NOT EXISTS 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pairwise_votes", type_="foreignkey")
    op.drop_constraint(None, "pairwise_votes", type_="foreignkey")
    op.drop_constraint(None, "pairwise_votes", type_="foreignkey")
    op.create_foreign_key(
        op.f("pairwise_votes_competition_id_fkey"),
        "pairwise_votes",
        "competitions",
        ["competition_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("pairwise_votes_loser_entry_id_fkey"),
        "pairwise_votes",
        "competition_entries",
        ["loser_entry_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("pairwise_votes_winner_entry_id_fkey"),
        "pairwise_votes",
        "competition_entries",
        ["winner_entry_id"],
        ["id"],
    )
    op.drop_constraint(None, "competition_entries", type_="foreignkey")
    op.create_foreign_key(
        op.f("competition_entries_competition_id_fkey"),
        "competition_entries",
        "competitions",
        ["competition_id"],
        ["id"],
    )
    # ### end Alembic commands ###
