"""Updated users table and added follower table

Revision ID: c83e80ed2da5
Revises: 49420e2f473e
Create Date: 2025-04-24 13:55:29.280427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83e80ed2da5'
down_revision: Union[str, None] = '49420e2f473e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.UUID(), nullable=False),
    sa.Column('user_id2', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'bio')
    op.drop_table('followers')
    # ### end Alembic commands ###
