"""empty message

Revision ID: cf3e615d2577
Revises: 9ec1aea65572
Create Date: 2025-08-06 11:36:11.355283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3e615d2577'
down_revision: Union[str, None] = '9ec1aea65572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairwise_votes', sa.Column('entry_id_1', sa.UUID(), nullable=False))
    op.add_column('pairwise_votes', sa.Column('entry_id_2', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_user_pair_per_competition', 'pairwise_votes', ['user_id', 'competition_id', 'entry_id_1', 'entry_id_2'])
    op.drop_constraint(op.f('pairwise_votes_loser_entry_id_fkey'), 'pairwise_votes', type_='foreignkey')
    op.create_foreign_key(None, 'pairwise_votes', 'competition_entries', ['entry_id_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pairwise_votes', 'competition_entries', ['entry_id_1'], ['id'], ondelete='CASCADE')
    op.drop_column('pairwise_votes', 'loser_entry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairwise_votes', sa.Column('loser_entry_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pairwise_votes', type_='foreignkey')
    op.drop_constraint(None, 'pairwise_votes', type_='foreignkey')
    op.create_foreign_key(op.f('pairwise_votes_loser_entry_id_fkey'), 'pairwise_votes', 'competition_entries', ['loser_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_pair_per_competition', 'pairwise_votes', type_='unique')
    op.drop_column('pairwise_votes', 'entry_id_2')
    op.drop_column('pairwise_votes', 'entry_id_1')
    # ### end Alembic commands ###
